### ISSUE TITLE
代码本身有race condition

### ISSUE THREAD

**Issue by cannium** [funny/sync#3]
在尝试用您的代码debug [InfluxDB](https://github.com/influxdb/influxdb)，结果发现sync本身有race conditoin。golang的Data Race Detector输出见https://gist.github.com/cannium/66a752ace83ddb80d2a7

看您有什么想法?

**Comment by cannium** [comment]
貌似是因为对`monitor.holders`的访问没加锁，我再尝试一下

**Comment by idada** [comment]
是的，release没加锁导致的，我也在细看，代码写完放那里很久了，需要断点续传一下。。。

**Comment by cannium** [comment]
Cool. Close the issue.
